### ISSUE TITLE
Cannot prune unused images

### ISSUE THREAD

**Issue by bonotake** [eldesh/dockworker#31]
`Docker::prune_images()` is not working now. When I called it, message `Invalid filter 'filters'` appeared.

As noted in #21, it runs on the latest API version (regarding mine, v1.39) where the `filters` parameter is gone. 
This may be solved by solving #21, or deleting the following lines:
https://github.com/eldesh/dockworker/blob/a2fb30e6d93035a48dcf4607551b8219cc75b57e/src/docker.rs#L710-L713

**Comment by bonotake** [comment]
I was wrong. v1.39 has `filters` parameter exists as well as v1.26.
https://docs.docker.com/engine/api/v1.39/#operation/ImagePrune
https://docs.docker.com/engine/api/v1.26/#operation/ImagePrune

So I suspect the JSON value has something wrong, but I don't understand how to fix it.

**Comment by eldesh** [comment]
fixed with #32
