### ISSUE TITLE
container_info returns json error

### ISSUE THREAD

**Issue by idanski** [eldesh/dockworker#58]
Hi,

Running this code:
```rust
let container_id = "e50fa516f9b684591b4b9180a3751d44a3b24a1471f9987b5034b727c91cad37";

let docker = Docker::connect_with_defaults().unwrap();
match docker.container_info(container_id) {
    Ok(result) => println!("{:?}", result),
    Err(e) => println!("Error: {}", e) 
}
```

produces `Error: json error`

I can't figure out the root cause. Am I doing something wrong?

The container_id is fine, I am able to get a valid json when manually running:
```
curl --unix-socket /var/run/docker.sock http://docker/containers/e50fa516f9b684591b4b9180a3751d44a3b24a1471f9987b5034b727c91cad37/json
```

**Comment by eldesh** [comment]
👀

**Comment by idanski** [comment]
Hi thanks!
After further investigation it seems the first '{' character that opens the return json is dropped from the buffer.

I even wrote a test to reproduce it, I did not yet understand why that happens.


docker --version out put is:
`Docker version 19.03.1-ce, build 74b1e89e8a`

**Comment by idanski** [comment]
Hey, I found the problem, I think.
Turns out the inspect/info fails for *some* of my dockers.

The reason for this as I understand it is that inside DockerInfo.Config - the volumes are defined as 

```rust
/// This type represents a `struct{}` in the Go code.
pub type UnspecifiedObject = HashMap<String, String>;
// ...
#[serde(deserialize_with = "null_to_default")]
pub Volumes: UnspecifiedObject,
```

While a docker inspect I did for a local docker has, for example:
```
            "Volumes": {
                "/etc/grafana/provisioning": {},
                "/var/lib/grafana/config.monitoring": {},
                "/var/lib/grafana/dashboards": {}
            },
```

I'll open a PR to fix soon.
