### ISSUE TITLE
Move Repo to a Standalone ( non-fork ) Repository

### ISSUE THREAD

**Issue by zicklag** [eldesh/dockworker#73]
To increase discoverability on GitHub I think it would be good to migrate the repository to a standalone repository so that it will pop up in GitHub searches. I almost didn't find it because I found the repository that it was forked from instead.

You have to contact GitHub support to have them migrate the repo: https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork.

**Comment by eldesh** [comment]
Thank you for your advice.
I have requested migration to github support.

**Comment by eldesh** [comment]
Github developer support has finished detaching this repository.
