### ISSUE TITLE
Docs.rs Build Broken for 0.14 and 0.15

### ISSUE THREAD

**Issue by zicklag** [eldesh/dockworker#74]
For some reason the docs are broken for 0.0.14 and 0.0.15. I'm not sure if that is the fault of this crate or Docs.rs, but it would be good to figure that out.

**Comment by eldesh** [comment]
Thank you for reporting.
I know that problem, but I can't come up with any reason :cry:

**Comment by eldesh** [comment]
I have reported this issue. https://github.com/rust-lang/docs.rs/issues/555

**Comment by eldesh** [comment]
FYI: Now, documents of [0.0.16](https://docs.rs/dockworker/0.0.16/dockworker/index.html) is available.

**Comment by zicklag** [comment]
Awesome, that's good enough for me. :) I'll close this, but if you want to get the other builds working you could re-open it.
